### ISSUE TITLE
Set up getdkan.org

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/website#1]
Set up DNS for https://getdkan.github.io/website/ to map to getdkan.org.

**Comment by aaronpava** [comment]
@lukefretwell Who owns the URL getdkan.org ?

**Comment by aaronpava** [comment]
@lukefretwell According to Whois @andrewhoppin owns the domain. Do we need access from him or do we already have it?

**Comment by lukefretwell** [comment]
@andrewhoppin do you know the status of this?

**Comment by andrewhoppin** [comment]
@aaronpava @lukefretwell happy to transfer ownership-- can you initiate a transfer request from your registrar?  I have it at GoDaddy.

**Comment by lukefretwell** [comment]
@aaronpava @grugnog did this get resolved? See @andrewhoppin's comment ^^.

**Comment by lukefretwell** [comment]
@andrewhoppin sounds like you're the blocker. Can you sync with @grugnog ASAP to finalize.
