### ISSUE TITLE
Add code of conduct to summit page

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/website#13]

**Comment by lukefretwell** [comment]
@nerdstein @grugnog @andrewhoppin thoughts on who lead creating this? I think it's as simple as modifying this and posting to docs:

http://stumptownsyndicate.org/code-of-conduct/

**Comment by grugnog** [comment]
@lukefretwell that looks like a good start. We probably need a CoC for Slack also.

**Comment by lukefretwell** [comment]
@grugnog who would be best to lead this? Do you think the Slack/event CoCs should be different?

**Comment by lukefretwell** [comment]
@grugnog moving this to here and closing this issue: 

https://github.com/GetDKAN/ops/issues/36
