### ISSUE TITLE
"What are you looking for?" / engage / feedback feature

### ISSUE THREAD

**Issue by nerdstein** [GetDKAN/website#16]
I would love to see a data input form that someone can search for or enter some text that we can get some insight for feedback into the product.

**Comment by lukefretwell** [comment]
@nerdstein where are the areas we should direct folks to give feedback?

Would be great to combine this issue with this and expound: 

https://github.com/GetDKAN/website/issues/12

**Comment by lukefretwell** [comment]
- [ ] establish consistent release schedule (ex: last day of the month)
- [ ] add how to give feedback on website (new page?) + docs?
- [ ] blog post announcing updates
- [ ] share blog post to community (social, Slack, etc.)

**Comment by lukefretwell** [comment]
Added this to community page: https://getdkan.org/community/
