### ISSUE TITLE
/community page is unclear

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/website#21]
When I go to /community, I should see a clear call to action, so I want to join the community and know what will happen when I click to do so.

Options:
- "Join the conversation around DKAN and open data" (Join button with Slack logo next to it)
- "Want to get involved with DKAN? Join the conversation on [Slack](dkan.slack.com); submit suggestions or bugs to the [Github issue queue](github.com/GetDKAN/dkan); follow the [blog](medium.com/dkan-blog); or find us on [Facebook](facebook.com/getdkan), [Twitter](twitter.com/getdkan), [LinkedIn](linkedin.com/in/getdkan), Medium, or Reddit."

**Comment by lukefretwell** [comment]
@kimwdavidson updated: https://getdkan.org/community/

**Comment by kimwdavidson** [comment]
Love the new page!
