### ISSUE TITLE
Create a community modules page on getdkan.org

### ISSUE THREAD

**Issue by nerdstein** [GetDKAN/website#23]
It would be nice if we had a directory of community sponsored modules listed on the website. It could be a list of name, purpose, and link to the code repo.

Here are a few from Angry Cactus: 

1.  https://github.com/angrycactus/dkan-harvest-collector - Add the concept of "data.json collectors"
2. https://github.com/angrycactus/dkan-harvest-secop - And a plugin for the above module that crawls a government website for csv links and collects them into a data.json file for harvesting by the harvester

There will certainly be more.

**Comment by lukefretwell** [comment]
@nerdstein for now, I'll add a 'Modules' page to docs.

FYI I asked AC if they could add more info to the repos: 

* https://github.com/angrycactus/dkan-harvest-secop/issues/1
* https://github.com/angrycactus/dkan-harvest-collector/issues/1

**Comment by kimwdavidson** [comment]
Moved here: github.com/GetDKAN/dkan/issues/2348 Closing
