### ISSUE TITLE
Add team members + social links

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/website#4]
Who else should be included? 

Here's what we need from each person (add your info in the comments):

* Name: 
* Twitter link: 
* LinkedIn link:
* GitHub link: 
* headshot

**Comment by lukefretwell** [comment]
@dafeder @andrewhoppin who else should be added to this that's not on this page?

https://getdkan.github.io/website/

**Comment by dangur** [comment]
Name: Dan Gurin
Twitter link: https://twitter.com/DGurin
LinkedIn link: https://www.linkedin.com/in/dangur/
GitHub link: https://github.com/dangur
headshot: https://avatars1.githubusercontent.com/u/307044?v=4&s=460

**Comment by dafeder** [comment]
Name: Dan Feder
Twitter: https://twitter.com/dafeder
LinkedIn: https://www.linkedin.com/in/daniel-feder-1450a915/
Github: https://github.com/dafeder

**Comment by dkinzer** [comment]
Name: David Kinzer
Twitter link: https://twitter.com/dtkinzer
LinkedIn: https://www.linkedin.com/in/dkinzer/
GitHub link: https://github.com/dkinzer

**Comment by stefaniefgray** [comment]
Name: Stefanie Gray
Twitter: N/A
Personal Site: http://www.stefaniefgray.com
GitHub link: https://github.com/stefaniefgray

**Comment by lukefretwell** [comment]
@stefaniefgray @dafeder @dangur @dkinzer updated: https://getdkan.github.io/website/

@andrewhoppin can you add yours?

@acouch you, too?

@dafeder who else? Can you point them to this?

I'm going to close this issue by 5:00 p.m. PT today.

**Comment by janette** [comment]
Name: Janette Day
Twitter link: n/a
LinkedIn link: https://www.linkedin.com/in/janette-day-7080841/
GitHub link: https://github.com/janette

**Comment by andrewhoppin** [comment]
Name: Janette Day
Twitter link: https://twitter.com/ahoppin
LinkedIn link: https://linkedin.com/in/ahoppin
GitHub link: https://github.com/andrewhoppin
