### ISSUE TITLE
Move http://www.dkansummit.org/ to /summit

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/website#5]
- [x] Move the summit repo (https://github.com/GetDKAN/summit) to /summit in this repo.
- [ ] Redirect dkansummit.org to getdkan.org/summit
- [x] Delete repo: https://github.com/GetDKAN/summit

**Comment by lukefretwell** [comment]
@aaronpava OK to redirect dkansummit.org to getdkan.org/summit now.

**Comment by lukefretwell** [comment]
@grugnog: @aaronpava did this, but it still isn't redirecting. Can you take a look when you have a chance?

**Comment by lukefretwell** [comment]
@aaronpava looks like you're going to need to take care of this. @grugnog says he doesn't have access to this domain.

**Comment by lukefretwell** [comment]
@aaronpava @grugnog ping ^^

**Comment by lukefretwell** [comment]
@aaronpava @grugnog ping ^^

Can we resolve this week?

**Comment by lukefretwell** [comment]
@grugnog @aaronpava working on websites issues and cleaning this out. Moving last item to ops backlog.

**Comment by grugnog** [comment]
Wildcard redirect set up - may take a while for nameservers to update before it is active
