### ISSUE TITLE
General feedback on https://getdkan.github.io/website/

### ISSUE THREAD

**Issue by bobschmitt-civicactions** [GetDKAN/website#6]
1) First words I read were: 
"DKAN is used by public and private sector organizations throughout the world."

First question: TO DO WHAT? To me (naive non-technical program manager) Who it's used by seems secondary to the problem the platform is meant to solve. My recommendation would be to phrase it so that what it does precedes who uses it, e.g.:

Open data visualization tools for the public sector.

or

Making data accessible to the public.

2) What does DKAN stand for? Why the acronym? I keep trying to figure out why it's named that. I suspect others have the same question.

3) The Features icons/names should be ordered to sell to a naive program manager, NOT a technologist. Some features I thought that DKAN provides and are sellable that I didn't find on the list of features are:

• Community driven feature development
• Manage diverse data sets
• Advanced visualization tools
• Mature user interface and workflow

Thats it. Love the UI and color scheme.

**Comment by dafeder** [comment]
> What does DKAN stand for? Why the acronym? I keep trying to figure out why it's named that. I suspect others have the same question.

DKAN is a Drupal-based open data portal based on CKAN, the first widely adopted open source open data portal software. CKAN stands for Comprehensive Knowledge Archive Network. It has inspired at least one other variant - JKAN, which is built on Jekyl. There have been references in print to the "*KAN space." I don't think of DKAN really being an acronym for anything. Perhaps some version of this narrative could go on the website or documentation.  

I agree something like "DKAN is used by public and private sector organizations throughout the world to make data more accessible to civil society." would be more meaningful. Although, I would note it says "open data" twice in the heading and that's a term with a fairly accepted definition. 

I also think the primary audience for this page is people with a certain level of open data literacy, and while we might want to rethink the features list to some degree we don't need to be too cautious about domain-specific language.

**Comment by bobschmitt-civicactions** [comment]
Thanks! This is a lot more clear now. I think we really do need:

> DKAN is a Drupal-based open data portal based on CKAN, the first widely adopted open source open data portal software. CKAN stands for Comprehensive Knowledge Archive Network. It has inspired at least one other variant - JKAN, which is built on Jekyl. 

as part of the intro somewhere. And, we should probably latch onto DKAN is an acronym for: Drupal-based Knowledge Archive Network. That helps bound it in my head at least.

My feeling about "open data" as a marketing/positioning concept is that it's incredibly vague. I think we can/should be more descriptive about what that means to us/our perceived market, and how DKAN adds value to it.

We might consider structuring a paragraph or two based on the Arno Penzias' data-information-knowledge-wisdom construct to describe how DKAN structures data into information to build knowledge and inform wise policy choices.

**Comment by lukefretwell** [comment]
@bobschmitt-civicactions @dafeder added DKAN relationship to CKAN here: 

https://github.com/GetDKAN/dkan/pull/2257

**Comment by lukefretwell** [comment]
@bobschmitt-civicactions updated features section per your input.
