### ISSUE TITLE
Create universal nav and footer includes

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/website#7]
I'd like to be able to manage the navigation and footer in one file or files (currently they're hard-coded on the following pages:

* https://getdkan.github.io/website/
* https://getdkan.github.io/website/brand/index.html
* https://getdkan.github.io/website/summit/index.html

**Comment by lukefretwell** [comment]
@grugnog @aaronpava anyone we can get to help with this?

**Comment by grugnog** [comment]
@lukefretwell I think you may be able to do this by moving the header markup to a header.html file and then including it using an include tag like `{% include /header.html %}` (see https://jekyllrb.com/docs/includes/). If you are looking for engineering support I would suggest asking Kim to see who is available.

**Comment by grugnog** [comment]
@lukefretwell I won't have time to do this for a while - please ask Kim if you are looking for support

**Comment by lukefretwell** [comment]
@grugnog thank you. cc @kimwdavidson can you help with this?

**Comment by lukefretwell** [comment]
@grugnog I'm going to close this for now.
