### ISSUE TITLE
Redirect getdkan.com to getdkan.org

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/website#8]
* redirect getdkan.com to getdkan.org
* redirect all /* pages on getdkan.com to getdkan.org main

**Comment by grugnog** [comment]
@lukefretwell let me know if you are ready to do this now

**Comment by grugnog** [comment]
@lukefretwell was you adding that label you asking me to work on this? ;)

**Comment by lukefretwell** [comment]
@grugnog yep. :-) Just not sure what else needs to be done so we don't "break" anything. Maybe a quick chat?

**Comment by grugnog** [comment]
@lukefretwell ping me on Slack if you would like to chat. FWIW the description seems clear to me and I don't foresee anything breakable given that it is a static site (and I can switch back quickly if we do discover something). I think the main question is if I should do this right away or if you want to wait for a specific date/time.

**Comment by aaronpava** [comment]
My understanding was we were waiting until transition was over, so we can do now. @grugnog
