### ISSUE TITLE
SEO pass

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/website#9]
https://www.google.com/webmasters/#?modal_active=none

**Comment by aaronpava** [comment]
@kevwalsh - Can you help with this one?

**Comment by kevwalsh** [comment]
@aaronpava possibly. do we have a marketing plan somewhere that i could use as a starting place? like, who is the audience, what are our success criteria? is there a google analytics account showing historical trends that we can use as a baseline? Typically this would be at least a few hours work, i can probably find time in the next couple weeks.

**Comment by lukefretwell** [comment]
@kevwalsh I just want to do the bare minimum right now. I verified under Google Webmaster Tools, but would be great to add take care of robots.txt and sitemap (and anything else that's low-hanging fruit).

*  https://www.google.com/webmasters/tools/robots-testing-tool?hl=en&authuser=4&siteUrl=http://www.getdkan.org/
* https://www.google.com/webmasters/tools/sitemap-list?hl=en&authuser=4&siteUrl=http://www.getdkan.org/#MAIN_TAB=1&CARD_TAB=-1

Added you and @grugnog to full access rights for search console.

**Comment by lukefretwell** [comment]
@kevwalsh any thoughts? cc @kimwdavidson

**Comment by kevwalsh** [comment]
@lukefretwell sitemap.xml and robots.txt here: https://github.com/GetDKAN/website/pull/17

**Comment by lukefretwell** [comment]
@kevwalsh thank you! ❤️
